### ISSUE TITLE
Extra add-on: Make sidebar fixed

### ISSUE THREAD

**Issue by mistermantas** [12px/eddited#2]
The idea for a fixed sidebar is that it gives users a quicker way to submit posts and also see the rules, other info, and stuff.

You could use something like this (but please don’t; you can’t scroll on the sidebar with this of a hack):

![image](https://user-images.githubusercontent.com/11616378/29073714-4afc6a16-7c55-11e7-874f-8f0b1bb8f285.png)

I’ve made it work before, I can’t remember what I exactly did though.

```css
.side {
    margin: 33px 0 0;
    width: 300px;
    border-left: 1px solid #eaeaea;
    -ms-flex-order: 2;
    order: 2;
    position: fixed;
    overflow-y: scroll;
    top: 6px;
    right: 0;
    z-index: 9999999;
}
```
